#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT="$ROOT/docs/verification/latest.md"
mkdir -p "$(dirname "$REPORT")"

run_section() {
	local title="$1"
	shift

	{
		printf '\n## %s\n\n' "$title"
		printf 'Command:\n\n```bash\n'
		printf '%q ' "$@"
		printf '\n```\n\n'
		printf 'Output:\n\n```text\n'
	} >> "$REPORT"

	if "$@" >> "$REPORT" 2>&1; then
		printf '```\n\nResult: PASS\n' >> "$REPORT"
	else
		local code=$?
		printf '```\n\nResult: FAIL (exit %s)\n' "$code" >> "$REPORT"
		return "$code"
	fi
}

write_header() {
	{
		printf '# Launch Verification Proof\n\n'
		printf 'Generated: %s\n\n' "$(date -u '+%Y-%m-%d %H:%M:%S UTC')"
		printf 'Repo: `%s`\n\n' "$ROOT"
		printf 'This file is generated by `scripts/verify-launch.sh`.\n'
	} > "$REPORT"
}

write_header
cd "$ROOT"

run_section "Git State" bash -lc 'git rev-parse HEAD && git ls-remote origin refs/heads/main && git status --short --ignored'

run_section "GitHub Pages Workflow" bash -lc 'gh run list --workflow "Deploy static content to Pages" --branch main --limit 1 --json databaseId,headSha,status,conclusion,url | php -r '\''$runs=json_decode(stream_get_contents(STDIN), true); foreach($runs as $r){echo "run=".$r["databaseId"]."\nheadSha=".$r["headSha"]."\nstatus=".$r["status"]."\nconclusion=".($r["conclusion"]??"")."\nurl=".$r["url"]."\n"; if(($r["status"]??"")!=="completed" || ($r["conclusion"]??"")!=="success") exit(1);}'\'''

run_section "Public GitHub Pages URLs" bash -lc 'for url in "https://yasircs4.github.io/wp-plg-arabic-search-enhancement/?verify=1" "https://yasircs4.github.io/wp-plg-arabic-search-enhancement/blog/?verify=1" "https://yasircs4.github.io/wp-plg-arabic-search-enhancement/blog/launch-1-4-8.html?verify=1" "https://yasircs4.github.io/wp-plg-arabic-search-enhancement/marketing/?verify=1"; do code=$(curl -L -sS -A "ASEVerify/1.0" -o /tmp/ase-page.html -w "%{http_code}" "$url"); title=$(php -r '\''$html=file_get_contents("/tmp/ase-page.html"); preg_match("/<title>(.*?)<\\/title>/is",$html,$m); echo trim(preg_replace("/\\s+/"," ",$m[1]??""));'\''); echo "$url http=$code title=$title"; test "$code" = "200"; rg -q "Arabic Search Enhancement" /tmp/ase-page.html; done'

run_section "Public Pages Playwright Smoke" npm run pages:smoke

run_section "WordPress.org API" bash -lc 'curl -L -sS -A "ASEVerify/1.0" "https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&request%5Bslug%5D=arabic-search-enhancement" -o /tmp/ase-wporg-api.json && php -r '\''$j=json_decode(file_get_contents("/tmp/ase-wporg-api.json"), true); foreach(["name","slug","version","tested","download_link"] as $k){echo "$k=".($j[$k]??"")."\n";} if(($j["version"]??"") !== "1.4.8") exit(1);'\'''

run_section "WordPress.org Plugin Page" bash -lc 'curl -L -sS -A "ASEVerify/1.0" -o /tmp/ase-wporg-page.html -w "http=%{http_code} url=%{url_effective}\n" https://wordpress.org/plugins/arabic-search-enhancement/; rg -q "softwareVersion.: .1\\.4\\.8|Version <strong>1\\.4\\.8</strong>|arabic-search-enhancement\\.1\\.4\\.8\\.zip" /tmp/ase-wporg-page.html'

run_section "WordPress.org SVN Listing" bash -lc 'svn ls https://plugins.svn.wordpress.org/arabic-search-enhancement/ && svn ls https://plugins.svn.wordpress.org/arabic-search-enhancement/trunk/ && svn ls https://plugins.svn.wordpress.org/arabic-search-enhancement/tags/ && svn ls https://plugins.svn.wordpress.org/arabic-search-enhancement/assets/'

run_section "WordPress.org ZIP Scan" bash -lc 'zip=/tmp/arabic-search-enhancement.1.4.8.verify.zip; curl -L -sS -A "ASEVerify/1.0" -o "$zip" https://downloads.wordpress.org/plugin/arabic-search-enhancement.1.4.8.zip; unzip -tq "$zip"; unzip -Z1 "$zip" | tee /tmp/ase-zip-list.txt; ! rg -n "(^|/)(\\.git|\\.github|docs|tests|vendor|node_modules|wporg-assets|composer\\.|package(-lock)?\\.json|phpunit\\.xml|SVN credentials\\.txt|\\.DS_Store|.*\\.zip)$" /tmp/ase-zip-list.txt'

run_section "WordPress.org Asset CDN" bash -lc 'for asset in banner-772x250.png banner-1544x500.png icon-128x128.png icon-256x256.png screenshot-1.png screenshot-2.png screenshot-3.png screenshot-4.png; do out="/tmp/ase-$asset"; code=$(curl -L -sS -A "ASEVerify/1.0" -o "$out" -w "%{http_code} %{content_type} %{size_download}" "https://ps.w.org/arabic-search-enhancement/assets/$asset"); echo "$asset $code"; file "$out"; done'

run_section "PHP Syntax" bash -lc 'find arabic-search-enhancement.php src tests -name "*.php" -print0 | xargs -0 -n1 php -l'

run_section "PHPUnit" vendor/bin/phpunit

run_section "WordPress.org Asset Dimensions" npm run wporg:validate-assets

run_section "Plugin Check Runtime Package" bash -lc 'runtime_dir=$(cat /tmp/ase-final-runtime-package-path.txt 2>/dev/null || true); if [ -z "$runtime_dir" ] || [ ! -d "$runtime_dir" ]; then runtime_dir=$(wporg-assets/src/build-runtime-package.sh); fi; ASE_WPORG_PLUGIN_DIR="$runtime_dir" ASE_WPORG_PORT=8099 docker compose -p ase-wporg-runtime -f wporg-assets/src/docker-compose.wporg.yml run --rm cli wp plugin install plugin-check --activate --force >/tmp/ase-plugin-check-install.log 2>&1 || cat /tmp/ase-plugin-check-install.log; ASE_WPORG_PLUGIN_DIR="$runtime_dir" ASE_WPORG_PORT=8099 docker compose -p ase-wporg-runtime -f wporg-assets/src/docker-compose.wporg.yml run --rm cli wp plugin check arabic-search-enhancement --slug=arabic-search-enhancement --mode=new --format=strict-json > /tmp/ase-plugin-check-runtime.json; php -r '\''$j=json_decode(file_get_contents("/tmp/ase-plugin-check-runtime.json"), true); if (!is_array($j)) { echo file_get_contents("/tmp/ase-plugin-check-runtime.json"); exit(1); } $errors=0; $warnings=0; foreach ($j as $row) { $type=strtoupper($row["type"] ?? $row["severity"] ?? ""); if ($type==="ERROR") $errors++; if ($type==="WARNING") $warnings++; } echo "plugin_check_total=".count($j)."\nplugin_check_errors=$errors\nplugin_check_warnings=$warnings\n"; exit($errors > 0 ? 1 : 0);'\'''

run_section "Local WordPress Blog Posts" bash -lc 'for url in "http://localhost:8098/arabic-search-enhancement-1-4-8-live/" "http://localhost:8099/arabic-search-enhancement-1-4-8-live/"; do code=$(curl -L -sS -o /tmp/ase-local-post.html -w "%{http_code}" "$url"); echo "$url http=$code"; test "$code" = "200"; rg -q "Download Arabic Search Enhancement from WordPress.org" /tmp/ase-local-post.html; done'

cat >> "$REPORT" <<'EOF'

## Known Gaps

- Remote WordPress blog publishing is not verified because this workspace does not contain a safe remote WordPress REST/WP-CLI credential or alias.
- Local Docker WordPress blog posts are verified on ports `8098` and `8099`.
- `plugins.trac.wordpress.org` can present browser checks to command-line verification; the public SVN URL is used as the machine-verifiable code link.
EOF

echo "$REPORT"
